# Development Specific Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_clinic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: rootpassword
    hikari:
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/smart_clinic
      auto-index-creation: true
  
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.smartclinic: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.security: DEBUG

app:
  security:
    jwt:
      secret: development-jwt-secret-key-change-in-production
      expiration: 86400000
    cors:
      allowed-origins: http://localhost:3000,http://localhost:80,http://localhost:8080
