# Docker Specific Configuration
spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/smart_clinic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: `${DB_ROOT_PASSWORD:rootpassword}
  
  data:
    mongodb:
      uri: mongodb://mongodb:27017/smart_clinic
  
  redis:
    host: redis
    port: 6379

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.smartclinic: DEBUG
    org.hibernate.SQL: DEBUG
