spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_clinic
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/smart_clinic
      database: smart_clinic
  
  main:
    web-application-type: servlet

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.smartclinic: DEBUG
    org.hibernate.SQL: DEBUG