version: '3.8'

services:
  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: smartclinic-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smart_clinic
      MYSQL_USER: clinic_user
      MYSQL_PASSWORD: clinic123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clinic-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      timeout: 20s
      retries: 10

  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: smartclinic-mongo
    environment:
      MONGO_INITDB_DATABASE: smart_clinic
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - clinic-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/smart_clinic --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  # Spring Boot Application
  app:
    build: .
    container_name: smartclinic-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/smart_clinic
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/smart_clinic
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql-db:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
      - clinic-network
    restart: unless-stopped

  # Frontend (Nginx)
  frontend:
    image: nginx:alpine
    container_name: smartclinic-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - clinic-network
    restart: unless-stopped

  # Redis for Session Management (Optional)
  redis:
    image: redis:alpine
    container_name: smartclinic-redis
    ports:
      - "6379:6379"
    networks:
      - clinic-network
    restart: unless-stopped

  # phpMyAdmin for Database Management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smartclinic-phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql-db
    networks:
      - clinic-network
    restart: unless-stopped

  # Mongo Express for MongoDB Management
  mongo-express:
    image: mongo-express
    container_name: smartclinic-mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8082:8081"
    depends_on:
      - mongodb
    networks:
      - clinic-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
  mongo_data:
    driver: local

networks:
  clinic-network:
    driver: bridge